print("Input")
Nama = input ("Nama                     :")
NIM = input ("NIM                      :")
Klsprl = input ("Kelas Paralel            :")
Ttl = input ("Tempat/Tanggal Lahir     :")
Alamat = input ("Alamat                   :")
Hobby = input ("Hobby                    :")
NoHP = input ("No.HP                    :")

print("\n")

print(f"Output")
print(f"Nama                    : {Nama}")
print(f"NIM                     : {NIM}")
print(f"Kelas Paralel           : {Klsprl}")
print(f"Tempat/Tanggal Lahir    : {Ttl}")
print(f"Alamat                  : {Alamat}")
print(f"Hobby                   : {Hobby}")
print(f"No.HP                   : {NoHP}")