print('Regina Silva Maharatini')

print('# # # #          #')
print('#       #        #')
print('#       #        #')
print('#       #        #')
print('# # # #          #')
print('#      #         #')
print('#       #        #')
print('#        #       #')